import json
from pathlib import Path

from config import OUTPUT_DIR, BASE_DIR

from loaders_rhrhaz00 import build_rhrhaz00_tables
from loaders_qualifications import (
    load_qualifications,
    load_person_qualification_history,
    load_training_events_and_participation,
)
from loaders_skills_programs import build_skills_programs_tables
from loaders_degreed import load_degreed_learning


def load_strategy_skill_mapping(mapping_filename: str = "strategy_skill_mapping.json"):
    """
    Helper to load strategy_skill_mapping.json (generated by generate_skill_mapping_with_llm.py).
    Returns:
        dict with structure:
        {
          "mappings": [
            {
              "strategy_skill_code": "...",
              "internal_skill_names": [...]
            },
            ...
          ]
        }
    If the file does not exist, returns None and prints a warning.
    """
    mapping_path = BASE_DIR / mapping_filename
    if not mapping_path.exists():
        print(
            f"Warning: {mapping_filename} not found at {mapping_path.resolve()}.\n"
            f"Run generate_skill_mapping_with_llm.py if you need strategy-skill mappings."
        )
        return None
    try:
        mapping_obj = json.loads(mapping_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        print(
            f"Warning: {mapping_filename} exists but is not valid JSON. "
            f"Path: {mapping_path.resolve()}"
        )
        return None

    # Optional: print a short summary
    mappings = mapping_obj.get("mappings", [])
    print(f"Loaded {len(mappings)} strategy skill mappings from {mapping_path.name}")
    for m in mappings:
        code = m.get("strategy_skill_code")
        names = m.get("internal_skill_names", [])
        print(f"  {code} -> {names}")

    return mapping_obj


def main():
    # 1) RHRHAZ00-based tables: persons, positions, tasks, ZP/ZS/ZX descriptions
    rhr_tables = build_rhrhaz00_tables()

    # 2) Qualifications and SAP training
    qualifications = load_qualifications()
    person_qualification_history = load_person_qualification_history()
    training_events, training_participation = load_training_events_and_participation()

    # 3) Skill mapping and programs
    skills_programs = build_skills_programs_tables()
    skill_mapping = skills_programs["skill_mapping"]
    programs = skills_programs["programs"]

    # 4) Degreed learning completions
    degreed_learning = load_degreed_learning()

    # 5) (Optional) Load strategy-skill mapping if present
    strategy_skill_mapping = load_strategy_skill_mapping()  # uses default filename

    # Save all tables to CSV
    tables_to_save = {
        # RHRHAZ00
        "persons": rhr_tables["persons"],
        "positions": rhr_tables["positions"],
        "person_position_history": rhr_tables["person_position_history"],
        "position_tasks": rhr_tables["position_tasks"],
        "task_z_links": rhr_tables["task_z_links"],
        "z_descriptions": rhr_tables["z_descriptions"],
        # Qualifications & training
        "qualifications": qualifications,
        "person_qualification_history": person_qualification_history,
        "training_events": training_events,
        "training_participation": training_participation,
        # Skills & programs
        "skill_mapping": skill_mapping,
        "programs": programs,
        # Degreed
        "degreed_learning": degreed_learning,
        # Note: we are not writing strategy_skill_mapping to CSV; it is JSON-based.
    }

    for name, df in tables_to_save.items():
        df.to_csv(OUTPUT_DIR / f"{name}.csv", index=False)
        print(f"Saved {name}.csv with {len(df)} rows")

    # If you want to also save the mapping as a CSV for inspection, you can do:
    if strategy_skill_mapping is not None:
        mappings = strategy_skill_mapping.get("mappings", [])
        if mappings:
            # Convert the list of dicts to a DataFrame and save as CSV
            import pandas as pd

            df_map = pd.DataFrame(mappings)
            df_map.to_csv(OUTPUT_DIR / "strategy_skill_mapping.csv", index=False)
            print(
                f"Saved strategy_skill_mapping.csv with {len(df_map)} rows "
                f"to {OUTPUT_DIR.resolve()}"
            )


if __name__ == "__main__":
    main()